package banco1;

import fuction.BD.User;
import fuction.BD.UserDAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author vitor
 */
public class PIX extends javax.swing.JFrame {
    User user = new User();
    /**
     * Creates new form PIX
     */
    public PIX() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IMAGE_user = new banco1.MyButton();
        NAME_user = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BT_1 = new banco1.MyButton();
        VALOR = new javax.swing.JLabel();
        BT_2 = new banco1.MyButton();
        BT_3 = new banco1.MyButton();
        BT_6 = new banco1.MyButton();
        BT_5 = new banco1.MyButton();
        BT_4 = new banco1.MyButton();
        BT_0 = new banco1.MyButton();
        BT_9 = new banco1.MyButton();
        BT_7 = new banco1.MyButton();
        BT_8 = new banco1.MyButton();
        BT_enviar = new banco1.MyButton();
        DELET = new banco1.MyButton();
        BT_voltar = new banco1.MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(24, 106, 37));
        jPanel2.setPreferredSize(new java.awt.Dimension(343, 191));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Olá,");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banco1/mundi_resized-removebg-preview_resized (3).png"))); // NOI18N
        jLabel2.setToolTipText("");

        IMAGE_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banco1/SGCAM_20221110_053352846_resized (1).jpg"))); // NOI18N
        IMAGE_user.setColor(new java.awt.Color(204, 204, 204));
        IMAGE_user.setRadius(30);
        IMAGE_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMAGE_userActionPerformed(evt);
            }
        });

        NAME_user.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NAME_user.setForeground(new java.awt.Color(255, 255, 255));
        NAME_user.setText(user.getNome());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NAME_user)
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(IMAGE_user, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(IMAGE_user, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NAME_user))
                .addGap(26, 26, 26))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PIX");

        BT_1.setForeground(new java.awt.Color(255, 255, 255));
        BT_1.setText("1");
        BT_1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_1.setRadius(50);
        BT_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_1ActionPerformed(evt);
            }
        });

        VALOR.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        VALOR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VALOR.setText("VALOR");

        BT_2.setForeground(new java.awt.Color(255, 255, 255));
        BT_2.setText("2");
        BT_2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_2.setRadius(50);
        BT_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_2ActionPerformed(evt);
            }
        });

        BT_3.setForeground(new java.awt.Color(255, 255, 255));
        BT_3.setText("3");
        BT_3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_3.setRadius(50);
        BT_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_3ActionPerformed(evt);
            }
        });

        BT_6.setForeground(new java.awt.Color(255, 255, 255));
        BT_6.setText("6");
        BT_6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_6.setRadius(50);
        BT_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_6ActionPerformed(evt);
            }
        });

        BT_5.setForeground(new java.awt.Color(255, 255, 255));
        BT_5.setText("5");
        BT_5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_5.setRadius(50);
        BT_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_5ActionPerformed(evt);
            }
        });

        BT_4.setForeground(new java.awt.Color(255, 255, 255));
        BT_4.setText("4");
        BT_4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_4.setRadius(50);
        BT_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_4ActionPerformed(evt);
            }
        });

        BT_0.setForeground(new java.awt.Color(255, 255, 255));
        BT_0.setText("0");
        BT_0.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_0.setRadius(50);
        BT_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_0ActionPerformed(evt);
            }
        });

        BT_9.setForeground(new java.awt.Color(255, 255, 255));
        BT_9.setText("9");
        BT_9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_9.setRadius(50);
        BT_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_9ActionPerformed(evt);
            }
        });

        BT_7.setForeground(new java.awt.Color(255, 255, 255));
        BT_7.setText("7");
        BT_7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_7.setRadius(50);
        BT_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_7ActionPerformed(evt);
            }
        });

        BT_8.setForeground(new java.awt.Color(255, 255, 255));
        BT_8.setText("8");
        BT_8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_8.setRadius(50);
        BT_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_8ActionPerformed(evt);
            }
        });

        BT_enviar.setForeground(new java.awt.Color(255, 255, 255));
        BT_enviar.setText("ENVIAR");
        BT_enviar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BT_enviar.setRadius(30);
        BT_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_enviarActionPerformed(evt);
            }
        });

        DELET.setForeground(new java.awt.Color(255, 255, 255));
        DELET.setText("X");
        DELET.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        DELET.setRadius(30);
        DELET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETActionPerformed(evt);
            }
        });

        BT_voltar.setForeground(new java.awt.Color(255, 255, 255));
        BT_voltar.setText("VOLTAR");
        BT_voltar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BT_voltar.setRadius(30);
        BT_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(VALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BT_1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(BT_2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(BT_3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BT_4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(BT_5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(BT_6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DELET, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(BT_7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT_8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BT_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(VALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT_7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT_9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(DELET, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BT_0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(BT_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>   
    private void BT_voltarActionPerformed(java.awt.event.ActionEvent evt) {                                          
       Tela_principal.main(null);
    }                                         


    private void IMAGE_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMAGE_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IMAGE_userActionPerformed

    private void BT_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_2ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"2";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_2ActionPerformed

    private void BT_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_3ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"3";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_3ActionPerformed

    private void BT_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_6ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"6";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_6ActionPerformed

    private void BT_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_5ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"5";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_5ActionPerformed

    private void BT_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_0ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"0";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_0ActionPerformed

    private void BT_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_9ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"9";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_9ActionPerformed

    private void BT_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_4ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"4";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_4ActionPerformed

    private void BT_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_8ActionPerformed
        // TODO add your handling code here:
        String VALORm = VALOR.getText();
        VALORm = VALORm+"8";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_8ActionPerformed

    private void BT_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_1ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"1";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_1ActionPerformed

    private void BT_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_7ActionPerformed
        String VALORm = VALOR.getText();
        VALORm = VALORm+"7";
        VALOR.setText(VALORm);
    }//GEN-LAST:event_BT_7ActionPerformed

    private void BT_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_enviarActionPerformed
       String envio = VALOR.getText();
       double valor = Double.parseDouble(envio);
       UserDAO DAO = new UserDAO();
       User user = new User();
       user.setSaque(valor);
       if ( DAO.verifyUP(2)) {
        user.setSaque(0);
         PIX_ENVIO pix = new PIX_ENVIO(valor);
       PIX_ENVIO.main(null);
       }else{
        System.out.println("Saldo insuficiente");
        System.out.println(user.getSaque());
       }
      
      
    }//GEN-LAST:event_BT_enviarActionPerformed
    private void DELETActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String VALORm = VALOR.getText();
        int pos = VALORm.length();
        VALORm = VALORm.substring(pos,pos);
        VALOR.setText(VALORm);
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PIX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PIX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private banco1.MyButton BT_voltar;
    private banco1.MyButton BT_0;
    private banco1.MyButton BT_1;
    private banco1.MyButton BT_2;
    private banco1.MyButton BT_3;
    private banco1.MyButton BT_4;
    private banco1.MyButton BT_5;
    private banco1.MyButton BT_6;
    private banco1.MyButton BT_7;
    private banco1.MyButton BT_8;
    private banco1.MyButton BT_9;
    private banco1.MyButton BT_enviar;
    private banco1.MyButton IMAGE_user;
    private javax.swing.JLabel NAME_user;
    private javax.swing.JLabel VALOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private banco1.MyButton DELET;
    // End of variables declaration//GEN-END:variables
}
