import javax.swing.event.ChangeEvent;

import banco1.Tela_principal;
import banco_davi.SUDO;
import banco_davi.SUDO_SU;
import banco_davi.teladobanco;
import fuction.BD.Login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */



/**
 *
 * @author vitor
 */
public class Login_final extends javax.swing.JFrame {
    public int i =0;
    boolean status = true;
    /** Creates new form Login */
    public Login_final() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SENHA_login = new textfield.PasswordField();
        CPF_login = new textfield.TextField();
        SENHA_esqueceu = new javax.swing.JLabel();
        BAR_progress = new progressbar.ProgressBarCustom();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MUNDI = new javax.swing.JLabel();
        BUTTON_entrar = new MyButton();
        BUTTON_criar = new MyButton();
        DEPOSITO = new MyButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SENHA_login.setLabelText("SENHA");
        SENHA_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SENHA_loginActionPerformed(evt);
            }
        });

        CPF_login.setLabelText("CPF");

        SENHA_esqueceu.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        SENHA_esqueceu.setText("Esqueceu a senha?");
        SENHA_esqueceu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SENHA_esqueceuMouseClicked(evt);
            }
        });

        BAR_progress.setForeground(new java.awt.Color(0, 102, 0));
        //BAR_progress.setValue();
        BAR_progress.setString("");
        BAR_progress.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BAR_progressStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");

        jPanel2.setBackground(new java.awt.Color(24, 106, 37));

        MUNDI.setBackground(new java.awt.Color(255, 255, 255));
        MUNDI.setFont(new java.awt.Font("Calibri", 1, 90)); // NOI18N
        MUNDI.setForeground(new java.awt.Color(255, 255, 255));
        MUNDI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MUNDI.setText("MUNDI");
        MUNDI.setToolTipText("");
        MUNDI.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MUNDIMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(MUNDI, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(MUNDI, javax.swing.GroupLayout.PREFERRED_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        BUTTON_entrar.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_entrar.setText("ENTRAR");
        BUTTON_entrar.setRadius(30);
        BUTTON_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_entrarActionPerformed(evt);
            }
        });

        BUTTON_criar.setForeground(new java.awt.Color(255, 255, 255));
        BUTTON_criar.setText("CRIAR CONTA");
        BUTTON_criar.setRadius(30);
        BUTTON_criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_criarActionPerformed(evt);
            }
        });

        DEPOSITO.setForeground(new java.awt.Color(255, 255, 255));
        DEPOSITO.setText("DEPOSITO");
        DEPOSITO.setRadius(30);
        DEPOSITO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPOSITOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BAR_progress, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BUTTON_criar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(DEPOSITO, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SENHA_esqueceu)
                    .addComponent(CPF_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SENHA_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTTON_entrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CPF_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SENHA_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SENHA_esqueceu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BUTTON_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTON_criar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DEPOSITO, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(BAR_progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SENHA_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SENHA_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SENHA_loginActionPerformed

    private void SENHA_esqueceuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SENHA_esqueceuMouseClicked
        // TODO add your handling code here:
       
        ESQUE.main(null);
    }//GEN-LAST:event_SENHA_esqueceuMouseClicked

    private void MUNDIMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MUNDIMouseMoved
        
    }//GEN-LAST:event_MUNDIMouseMoved

    private void BAR_progressStateChanged(javax.swing.event.ChangeEvent evt){//GEN-FIRST:event_BAR_progressStateChanged
       Thread Barra = new Thread(new Runnable() {
        @Override
            public void run(){
               while (status) {
               if (i<=100) {
                i+=10; 
                try {
                    Thread.sleep(500);
                } catch (Exception e) {
                    // TODO: handle exception
                }
               }else{
                 System.out.println("PAROU");
                    status = false;
                    Thread.interrupted();
               }
                System.out.println(i);
                BAR_progress.setValue(i);
               
               }
            }
       });
      
       Barra.start(); 
    }  
    private void DEPOSITOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPOSITOActionPerformed
        
    }//GEN-LAST:event_DEPOSITOActionPerformed

    private void BUTTON_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_entrarActionPerformed
        i=0;
        BAR_progressStateChanged(null);
        Login log = new Login();
        String cpf = CPF_login.getText();
        String senha = SENHA_login.getText();
        status = true;
        if (log.userSignIn(cpf,senha)) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
            Tela_principal.main(null);
        }else{
    System.err.println("erro");
        }
        if (cpf.equals("admin")&& senha.equals("admin")) {
            SUDO.main(null);
        }if (cpf.equals("adminSU")&& senha.equals("adminSU")) {
            SUDO_SU.main(null);
        }
      
        
    }//GEN-LAST:event_BUTTON_entrarActionPerformed


    private void BUTTON_criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_criarActionPerformed
        Cadastrar.Cadastrar_conta(null);
    }//GEN-LAST:event_BUTTON_criarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private progressbar.ProgressBarCustom BAR_progress;
    private MyButton BUTTON_criar;
    private MyButton BUTTON_entrar;
    private textfield.TextField CPF_login;
    private MyButton DEPOSITO;
    public javax.swing.JLabel MUNDI;
    private javax.swing.JLabel SENHA_esqueceu;
    private textfield.PasswordField SENHA_login;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
